### ISSUE TITLE
Donation Location?

### ISSUE THREAD

**Issue by ES-Alexander** [opencv/opencv-python#435]
Is there somewhere we can donate to help support the continued maintenance and development of this project? It's taken so much of the hassle out of building OpenCV from source thanks to the pre-built wheels and easy customisation options for source builds, which makes it much faster and easier to get up and running for both new users and new systems.

Having a donation source available might also be useful in spot hires of devs to help implement desirable features that @skvark isn't able or doesn't have the time to do.

**Comment by skvark** [comment]
Thanks! Currently, there is no way to donate, but I'll try to figure out if I can set up the Github sponsors feature. My primary concern with the donations is the Finnish tax system which is quite unclear and complex regarding donations and sponsorships.

**Comment by wycliffe-BI** [comment]
I second this: (I don't know how to use/compile C) when I first started using opencv-python I assumed it was the python SDK of the C code and it was maintained by the original community for the OpenCV project, i didn't realised it was maintained non-officially! I really appreciate the ease of use that has come about from having pre built wheels. It would definitely have put me off trying to use opencv had it not been for a python build.

**Comment by kohtala** [comment]
Since you two have offered, and @skvark has not asked for it, you can exchange money as a donation. You can exchange the payment privately to not confuse the issue making payment method public and appearing to be a requesting others to join. It can be a donation and if it stays [below 5000 € for three year period](https://www.finlex.fi/fi/laki/ajantasa/1940/19400378#L3P19a) for each donator, there is no tax to pay.

Looking at [the law](https://www.finlex.fi/fi/laki/ajantasa/2019/20190863), and the [groundwork](https://www.eduskunta.fi/FI/vaski/HallituksenEsitys/Sivut/HE_214+2018.aspx), it seems the interpretation is that since the software is available for free, you do not get anything in return for the money, and therefore you would need a permit to ask for donations or sponsorship. The permit can be given only for general interest. There would need to be a registered association or such to get the permit and show it is used for general interest and nothing else.

Tax office gave [some clarification](https://www.vero.fi/tietoa-verohallinnosta/uutishuone/uutiset/uutiset/2020/koronatilanne-toimi-n%C3%A4in-jos-saat-tuloa-somealustoilta-striimauksesta-tai-vastikkeellisista-rahoituskampanjoista/), but it does not help here. There would need to be something donors get access to only as result of payment to get into the normal income side of things.

It was a disappointment the recent change in law did not provide any help. Difficult to understand why you can not collect voluntary payment if you properly report it to tax office. I found some rationale the law is intended to protect those charitable causes that do get to collect donations. And it makes sense to protect those making the donations that money is used for the intended purpose. But here there is no such competition to protect and donors have already received what they pay for.

**Comment by skvark** [comment]
@kohtala Thanks, you summarized the situation well. I will not be setting up the Github sponsors feature.

Please note that the repository was re-located from my personal account to the OpenCV organization last week. The packages will be official in the future. Before that, I developed and maintained this project for about 5 years. The packages have been downloaded during that time over 100 million times and many companies, individual developers, as well as OSS projects, depend on them. 

There will people working on timely releases in the future and the project has now a much more stable future as it does not depend only on me and some occasional contributors. I believe there will be an official announcement about this at some point. I'll be one of the maintainers in some capacity until the transition is complete.

If you would like to contact me privately, you can send me email via op dot heinisuo at gmail dot com.

**Comment by kohtala** [comment]
Thanks for the work. I see the URL to skvark now redirects to opencv. Great to hear there is an organization behind to ensure security fixes (and more) get released even if you are not available.

I'm not a lawyer, but the subject of donations in Finland is interesting. Glad to make some use of the knowledge I've found on it.

I'm sure there are lot's of people happy to show gratitude, but if people get too enthusiastic and it gathers attention, I'm afraid people would create an appearance you were asking for money. So I think it would be best to close this issue, _not_ have any communication between you and donors public, to _not_ spread it any further and consider the issue resolved. Keep it between you and anyone who comes to you on their own initiative.

Saving any communication for ten years may be good idea, but more likely no-one will ask for it. After that it is an old issue. Tax office has great customer service these days, although they won't tell you upfront how to avoid paying taxes. Anyhow, sometimes asking them and reporting donation is a good thing even when taxes are not to be paid for the donation.

Donations from abroad may be subject to laws at the origin country.

Here an additional fresh link close to the subject at http://www.jussikari.fi/pelistriimaus-ja-laki-2021/.
