### ISSUE TITLE
Several model files of saliency_ObjectnessBING are missing 

### ISSUE THREAD

**Issue by ZhiZe-ZG** [opencv/opencv-python#457]
### Expected behaviour

Normally use saliency_ObjectnessBING

### Actual behaviour

```
Can't load model: /ObjNessB2W8MAXBGR.wS1 or /ObjNessB2W8MAXBGR.idx
Can't load model: /ObjNessB2W8HSV.wS1 or /ObjNessB2W8HSV.idx
Can't load model: /ObjNessB2W8I.wS1 or /ObjNessB2W8I.idx
```

### Steps to reproduce

opencv-python-comtrib 4.4

```python
import cv2 as cv
sa = cv.saliency_ObjectnessBING.create()
sa.computeSaliency(image)
```

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
@ZhiZe-ZG Thanks for the report. OpenCV-Contrib package does not include pre-trained models, even if they are  present in OpenCV-Contrib repository. It's done, because of large size, possible legal restrictions and unknown models quality. So, you need to put the models to known place and sent their location in algorithm properties.
- Pre-trained models in contrib repo: https://github.com/opencv/opencv_contrib/tree/master/modules/saliency/samples/ObjectnessTrainedModel
- Methods need to be called: `ObjectnessBING::setTrainingPath`, `ObjectnessBING::setBBResDir`, `ObjectnessBING::setColorSpace`, `ObjectnessBING::loadTrainedModel() `
