### ISSUE TITLE
Python3.5 aarch64 opencv-python wheel file installation

### ISSUE THREAD

**Issue by yushengsu** [opencv/opencv-python#468]
I have met the official website, but there is only a wheel file for python3.4.
Is there any way to install on my devices(Jetson AGX Xavier)

Architecture: aarch64
Python version: 3.5
OS: Ubuntu 18.04

**Comment by sergregory** [comment]
Hi @yushengsu, I do not have AGX Xavier, but have Nano, which should be pretty similar in terms of the software available.
It has Ubuntu 18.04 onboards, which provides the python3.6.9 as the default one and 3.7, 3.8, etc. are available from the repo.
For all of these python version pre-built opencv-python for aarch64 should be available from just the pip package manager (please check that you've updated your pip, since old releases do not recognize the new versions).

Regarding the python 3.5 - I think you're right and there are no pre-built packages. Is it critical for your project to work with python 3.5? Please note that this is pretty old release, which has reached its end-of-life, so the better decision would be to consider a newer release.

**Comment by yushengsu** [comment]
Yes, Python3.5 is critical for my project.
But I think it has a version for Python3.4, so it should be no reason for python3.5

**Comment by sergregory** [comment]
Could you please share with me the link to the official website with the wheel for python3.4?

**Comment by yushengsu** [comment]
Pypl said it can support python3.4 ~ 3.6
Link: https://pypi.org/project/opencv-python-aarch64/

**Comment by skvark** [comment]
Yeah, that package has been uploaded by some unknown person and it's using for example my name without permission. I would advise against using that package in case it contains malware or something. As @sergregory wrote, the only supported packages are the four variants listed in the description and in the README of this project. Python 3.5 is not supported because it is already EOL. Python 3.6 will be EOL during this year. Python 3.9 is recommended version. See: https://endoflife.date/python

Correct maintainers:

![maintainers](https://user-images.githubusercontent.com/695340/115910061-0d86d080-a475-11eb-8db6-025c43eb1190.PNG)

Incorrect maintainers:

![incorrect-maintainer](https://user-images.githubusercontent.com/695340/115910074-14adde80-a475-11eb-9dea-6f6c50d4d739.PNG)
