### ISSUE TITLE
Use other modules

### ISSUE THREAD

**Issue by S4pi3nti4** [opencv/opencv-python#490]
### Expected behaviour

from: opencv_contrib/samples/python2/video.py
import cv2 as cv
every cv.sfm method does not work

### Actual behaviour

the import statement does not work (at least it does not import he sfm module). I also tried another module which also didnt work.

### Steps to reproduce

I tried with 3 different setup:
1.1. "opencv-python"
1.2. "opencv-contrib-python"
1.3. "opencv-python" and "opencv-contrib-python"

2.1 import common 
2.2 or any other module (another example SFM module)

**Comment by asmorkalov** [comment]
SfM is part of OpenCV Contrib repo. Pre-built wheels available on Pypi (pip) does not contain SfM module, because it depends on several external math libs like Ceres. You can get SfM support if re-build OpenCV with all required options manually.
Also the is simple way to check exisitng OpenCV configuration with line `print(cv2.getBuildInformation())`. See [documentation](https://docs.opencv.org/master/db/de0/group__core__utils.html#ga0ae377100bc03ce22322926bba7fdbb5) for more details.
