### ISSUE TITLE
Vp09 encoding speeds up videos

### ISSUE THREAD

**Issue by rsoubi** [opencv/opencv-python#627]
### Expected behaviour

Using opencv-python video writer with **vp09** and **webm** container to save a video.

### Actual behaviour

The resulting video happens to be speeded up : it is 4 times faster than in real life. However the frame rate does not change.
e.g. 10 seconds recording at 20fps results in a 2,5 seconds clip at 20fps. The video start a normal frame rate for about 1 sec and then speeds up.

### Steps to reproduce

```
import cv2
import os
import time

CAPTURE_LENGTH = 10 #seconds

#Capture video from webcam
vid_capture = cv2.VideoCapture(0)
fourcc = cv2.VideoWriter_fourcc(*'vp09')
output = cv2.VideoWriter("cam_video.webm", fourcc, 20.0, (640,480))
start = time.time()

while(time.time() < start + CAPTURE_LENGTH):
     ret,frame = vid_capture.read()
     output.write(frame)
vid_capture.release()
output.release()
```

- operating system : tested on Ubuntu 18.04 x86 and windows 10 20H2 x86
- opencv-python version 4.5.2.52

**Comment by rsoubi** [comment]
Tested on opencv-contrib-python 4.5.5.62 : same issue

**Comment by asmorkalov** [comment]
@rsoubi Could you try the same code not with real time camera, but with video input or sequence of images. VideoEncoding is computationally heavy procedure. In case if video encoding takes more that 50ms (20 fps) than video encoder gets less frame than it should. 20fps is passed as video meta and players use it for playback. That's why you observe the speedup.
