### ISSUE TITLE
cv2.imwrite saving image problem

### ISSUE THREAD

**Issue by hungkawang** [opencv/opencv-python#664]
### Expected behaviour
Hi, I am build an API using docker and I am using cv2.VideoCapture and cv2.imwrite to capture an image from a rtsp link. I curl in postman and error occurred. The code suppose to try recapturing the image and finally print out "RTSP failed to capture." if trial > 10 or save the image to imgPath. My frame captured is None and it should raise error when cv2.imwrite(imgPath, frame)

### Actual behaviour

No error is raised when saving None and no file is found in the directory

### Steps to reproduce
![g2](https://user-images.githubusercontent.com/72651087/170426243-6a033083-1d16-48e6-b01e-1a1b9258369e.PNG)
![image](https://user-images.githubusercontent.com/72651087/170426668-67ab9558-07c1-4baa-b346-d66d5cbc24b5.png)

I am using opencv-python version 4.5.5.64 and python version 3.7.13

Thanks

**Comment by asmorkalov** [comment]
According to documentation it's expected behavior: https://docs.opencv.org/4.x/d8/dfe/classcv_1_1VideoCapture.html#a473055e77dd7faa4d26d686226b292c1 VideoCapture.read returns false and image set to None, if camera is disconnected or new frames are not available by some reason. Please ensure that your do not have issues with the network stream itself and the program is able to handle all frames on time.

**Comment by hungkawang** [comment]
But cv2.imwrite should raise error when you save None to imgPath?

**Comment by asmorkalov** [comment]
No, None is not valid Python object to be converted to C++ cv::Mat. So the issue with None is expected behaviour. In case if some parameter is not used or empty, please provide empty numpy.ndarray, but not None.
